#!/usr/bin/env python3
"""Generate Codex execution-policy rules from Claude Bash permissions.

Deliberately does not translate Claude's ``Read`` and ``Edit`` permissions.
Codex "execpolicy" rules only govern executable command prefixes. The generator
lists those omissions so a policy review cannot mistake them for coverage.
"""

import argparse
import json
import shlex
import sys
from collections.abc import Iterable
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / ".claude/settings.json"
DEFAULT_OUTPUT = ROOT / ".codex/rules/default.rules"
DECISIONS = (
    ("allow", "allow"),
    ("ask", "prompt"),
    ("deny", "forbidden"),
)


def bash_pattern(permission: str) -> list[str] | None:
    """Return a command prefix for a Claude Bash permission entry.

    Args:
        permission: A Claude permission string.

    Returns:
        Shell tokens for a Bash permission, or ``None`` for another permission
        type.
    """
    if permission.startswith("Bash(") and permission.endswith(")"):
        value = permission.removeprefix("Bash(").removesuffix(")")
        return shlex.split(value.removesuffix(":*"))
    else:
        return None


def starlark_list(tokens: Iterable[str]) -> str:
    """Render command tokens as a Starlark-compatible list.

    Args:
        tokens: Command-prefix tokens to serialize.

    Returns:
        A Starlark list literal.
    """
    items = ", ".join(repr(token) for token in tokens)
    return f"[{items}]"


def render(permissions: dict[str, object]) -> tuple[str, dict[str, int]]:
    """Render the rules file and return migration counts.

    Args:
        permissions: Claude permissions dictionary.

    Returns:
        Generated rule text and migration counts by permission class.

    Raises:
        ValueError: If the function fails to recognize format of the given
            dictionary.
    """
    if not isinstance(permissions, dict):
        raise ValueError("settings.json permissions must be an object")

    lines = [
        "# Generated by scripts/generate-codex-rules.py from .claude/settings.json.",
        "# Codex combines matching rules using the strictest decision.",
    ]
    counts = dict[str, int]()

    for source_name, decision in DECISIONS:
        entries = permissions.get(source_name, [])
        if not isinstance(entries, list) or not all(isinstance(entry, str) for entry in entries):
            raise ValueError(f"permissions.{source_name} must be a list of strings")

        command_patterns = [
            pattern
            for entry in entries
            if (pattern := bash_pattern(entry)) is not None
        ]

        counts[source_name] = len(command_patterns)
        counts[f"{source_name}_omitted"] = len(entries) - len(command_patterns)

        lines.extend(("", f"# Migrated Claude {source_name} rules."))
        for pattern in command_patterns:
            line = f"prefix_rule(pattern = {starlark_list(pattern)}, decision = '{decision}'"
            if decision == "prompt":
                line += ", justification = 'Requires explicit approval.'"
            elif decision == "forbidden":
                line += ", justification = 'Policy does not allow this usage.'"
            lines.append(line + ")")

    return "\n".join(lines) + "\n", counts


def non_command_permissions(permissions: dict[str, object]) -> dict[str, list[str]]:
    """Return Claude permissions that cannot become Codex execution rules.

    Args:
        permissions: Claude permissions dictionary.

    Returns:
        Non-Bash permission strings grouped by their Claude decision.
    """
    return {
        source_name: [entry for entry in permissions[source_name] if bash_pattern(entry) is None]
        for source_name, _ in DECISIONS
    }


def main() -> None:
    """Generate or verify Codex rules."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output file is not current instead of rewriting it",
    )
    args = parser.parse_args()
    settings = json.loads(args.source.read_text())
    permissions = settings["permissions"]
    rules, counts = render(permissions)
    omissions = non_command_permissions(permissions)

    if args.check:
        if args.output.exists():
            current = args.output.read_text()
        else:
            current = ""
        if current != rules:
            sys.exit(f"{args.output} is stale; run scripts/generate-codex-rules.py")
    else:
        args.output.write_text(rules)

    print(
        "Migrated Bash permissions: "
        f"allow={counts['allow']}, ask={counts['ask']}, deny={counts['deny']}. "
        "Unmigrated non-command permissions: "
        f"allow={counts['allow_omitted']}, ask={counts['ask_omitted']}, "
        f"deny={counts['deny_omitted']}."
    )
    for source_name, _ in DECISIONS:
        print(f"\nUnmigrated {source_name} permissions ({len(omissions[source_name])}):")
        for permission in omissions[source_name]:
            print(f"  {permission}")


if __name__ == "__main__":
    main()
