#!/usr/bin/env python3.14
"""Generate Codex execution-policy rules from Claude Bash permissions.

Claude's ``Read`` and ``Edit`` permissions are deliberately not translated:
Codex execpolicy rules only govern executable command prefixes. The generator
reports those omissions so a policy review cannot mistake them for coverage.
"""

import argparse
import json
import shlex
import sys
from collections.abc import Iterable
from pathlib import Path

type Decision = str

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / ".claude/settings.json"
DEFAULT_OUTPUT = ROOT / ".codex/rules/default.rules"
DECISIONS: tuple[tuple[str, Decision], ...] = (
    ("allow", "allow"),
    ("ask", "prompt"),
    ("deny", "forbidden"),
)


def bash_pattern(permission: str) -> list[str] | None:
    """Return a command prefix for a Claude Bash permission entry."""
    if not permission.startswith("Bash(") or not permission.endswith(")"):
        return None
    command = permission.removeprefix("Bash(").removesuffix(")")
    if command.endswith(":*"):
        command = command.removesuffix(":*")
    return shlex.split(command)


def starlark_list(tokens: Iterable[str]) -> str:
    """Render command tokens as a Starlark-compatible list."""
    return "[" + ", ".join(repr(token) for token in tokens) + "]"


def render(settings: dict[str, object]) -> tuple[str, dict[str, int]]:
    """Render the rules file and return migration counts."""
    permissions = settings["permissions"]
    if not isinstance(permissions, dict):
        raise ValueError("settings.json permissions must be an object")

    lines = [
        "# Generated by scripts/generate-codex-rules.py from .claude/settings.json.",
        "# Codex combines matching rules using the strictest decision.",
    ]
    counts: dict[str, int] = {}

    for source_name, decision in DECISIONS:
        entries = permissions.get(source_name, [])
        if not isinstance(entries, list) or not all(isinstance(entry, str) for entry in entries):
            raise ValueError(f"permissions.{source_name} must be a list of strings")

        command_patterns = [
            pattern for entry in entries if (pattern := bash_pattern(entry)) is not None
        ]
        omitted = len(entries) - len(command_patterns)
        counts[source_name] = len(command_patterns)
        counts[f"{source_name}_omitted"] = omitted

        lines.extend(("", f"# Migrated Claude {source_name} rules."))
        for pattern in command_patterns:
            line = f"prefix_rule(pattern = {starlark_list(pattern)}, decision = '{decision}'"
            if decision == "prompt":
                line += ", justification = 'Requires explicit approval.'"
            elif decision == "forbidden":
                line += ", justification = 'Blocked by the migrated Claude policy.'"
            lines.append(line + ")")

    return "\n".join(lines) + "\n", counts


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output file is not current instead of rewriting it",
    )
    return parser.parse_args()


def main() -> int:
    """Generate or verify Codex rules."""
    args = parse_args()
    settings = json.loads(args.source.read_text())
    rules, counts = render(settings)

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != rules:
            print(f"{args.output} is stale; run scripts/generate-codex-rules.py", file=sys.stderr)
            return 1
    else:
        args.output.write_text(rules)

    print(
        "Migrated Bash permissions: "
        f"allow={counts['allow']}, ask={counts['ask']}, deny={counts['deny']}. "
        "Unmigrated non-command permissions: "
        f"allow={counts['allow_omitted']}, ask={counts['ask_omitted']}, "
        f"deny={counts['deny_omitted']}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
